name: 'update doc'

on:
  pull_request:
    branches:
      - main
    types: [closed]

permissions:
  contents: write

jobs:
  private_action:
    uses: s-shima999/github-actions-test/.github/workflows/doc.yml@main
